- name: Create directory for SSL certs
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Generate self-signed SSL certificate
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/nginx/ssl/selfsigned.key
    -out /etc/nginx/ssl/selfsigned.crt
    -subj "/C=US/ST=Test/L=City/O=Org/OU=Unit/CN={{ domain_name }}"
  args:
    creates: /etc/nginx/ssl/selfsigned.crt